import LoadingWrapper from '@/components/LoadingWrapper'
import Layout from '@/Layout/Layout'
import { NextIntlClientProvider } from 'next-intl'
import { ThemeProvider } from 'next-themes'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default async function RootLayout({ children, params }) {
	const param = await params
	console.log(param)
	return (
		<html lang='en' className='dark'>
			<body className={`font-dmSans antialiased dark:bg-black bg-white`}>
				<NextIntlClientProvider>
					<ThemeProvider
						attribute='class'
						defaultTheme='system'
						enableSystem={true}
					>
						<Layout>
							<LoadingWrapper>{children}</LoadingWrapper>
						</Layout>
					</ThemeProvider>
				</NextIntlClientProvider>
			</body>
		</html>
	)
}
